limit_req_zone $binary_remote_addr zone=odoo_limit:10m rate=5r/s;

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name <YOUR DNS NAME WITHOUT THE HTTP>;
    return 301 https://$host$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name <YOUR DNS NAME WITHOUT THE HTTP>;

    ssl_certificate     /etc/letsencrypt/live/<YOUR DNS NAME WITHOUT THE HTTP>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<YOUR DNS NAME WITHOUT THE HTTP>/privkey.pem;

    # Basic SSL Security settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        limit_req zone=odoo_limit burst=10 nodelay;

        proxy_pass http://moodleapp:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https; # Force HTTPS scheme to Moodle
        proxy_set_header X-Forwarded-Port 443;
    }
}